import type { AiAssessment } from '@/types/api';

interface AIReportPanelProps {
  assessment: AiAssessment | null;
}

function renderList(data: unknown): string[] {
  if (Array.isArray(data)) return data.map(String);
  if (data && typeof data === 'object' && 'steps' in data) return (data as { steps: unknown[] }).steps.map(String);
  return [];
}

export function AIReportPanel({ assessment }: AIReportPanelProps) {
  if (!assessment) {
    return (
      <div className="text-sm text-gray-500 italic py-4 text-center">
        No AI assessment available.
      </div>
    );
  }

  const recs = assessment.recommendations ? renderList(assessment.recommendations) : [];
  const findings = assessment.key_findings ? renderList(assessment.key_findings) : [];

  return (
    <div className="space-y-4">
      {assessment.model_name && (
        <p className="text-xs text-gray-400">
          Generated by <strong>{assessment.model_name}</strong>
          {assessment.generation_time_ms != null && ` in ${assessment.generation_time_ms}ms`}
        </p>
      )}

      {assessment.executive_summary && (
        <div>
          <h4 className="text-sm font-semibold text-gray-700 mb-1">Executive Summary</h4>
          <p className="text-sm text-gray-600 leading-relaxed">{assessment.executive_summary}</p>
        </div>
      )}

      {findings.length > 0 && (
        <div>
          <h4 className="text-sm font-semibold text-gray-700 mb-1">Key Findings</h4>
          <ul className="list-disc list-inside text-sm text-gray-600 space-y-1">
            {findings.map((f, i) => (
              <li key={i}>{f}</li>
            ))}
          </ul>
        </div>
      )}

      {recs.length > 0 && (
        <div>
          <h4 className="text-sm font-semibold text-gray-700 mb-1">Recommendations</h4>
          <ul className="list-disc list-inside text-sm text-gray-600 space-y-1">
            {recs.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
