"""Thresholds and constants for Rule Engine detection rules.

Naming convention:
  _SUSPECT  = lowest threshold to be considered potentially suspicious
  _MEDIUM   = MEDIUM severity threshold
  _HIGH     = HIGH severity threshold
  _CRITICAL = CRITICAL severity threshold

Unless otherwise noted, all DNS query frequency thresholds are in
**queries per minute** (qpm), matching the Feature Extractor output scale.
"""

# Port Scan Rule
PORT_SCAN_SUSPECT_RATIO_MIN = 0.7  # extractor's failed-connection ratio flag
PORT_SCAN_CPM_LOW = 50.0  # connections per minute → lowest gate
PORT_SCAN_CPM_MEDIUM = 150.0  # connections per minute → MEDIUM
PORT_SCAN_CPM_HIGH = 600.0  # connections per minute → HIGH
PORT_SCAN_PORTS_MEDIUM = 20  # aligned with extractor PORT_SCAN_PORT_THRESHOLD
PORT_SCAN_PORTS_HIGH = 50
PORT_SCAN_PORTS_CRITICAL = 200

# DNS Tunneling Rule  (all frequencies in queries per minute)
DNS_BASE64_RATIO_SUSPECT = 0.3
DNS_BASE64_RATIO_HIGH = 0.7
DNS_SUBDOMAIN_COUNT_SUSPECT = 20
DNS_SUBDOMAIN_COUNT_HIGH = 50
DNS_ENTROPY_SUSPECT = 4.0
DNS_ENTROPY_HIGH = 5.5
DNS_QUERY_FREQ_PER_DOMAIN_SUSPECT = 60.0  # qpm (≈ 1 query/sec)
DNS_QUERY_FREQ_PER_DOMAIN_HIGH = 200.0  # qpm
DNS_QUERY_FREQ_PER_IP_SUSPECT = 20.0  # qpm

# FTP Brute Force Rule
FTP_FAILED_AUTH_RATIO_SUSPECT = 0.7
FTP_FAILED_AUTH_COUNT_MIN = 3
FTP_AUTH_RATE_SUSPECT = 0.3
FTP_AUTH_RATE_HIGH = 1.0

# SMTP Abuse Rule
SMTP_FAILED_AUTH_COUNT_SUSPECT = 3
SMTP_UNIQUE_RECIPIENTS_SUSPECT = 25  # avoid newsletter FPs
SMTP_UNIQUE_RECIPIENTS_HIGH = 100
SMTP_MESSAGE_COUNT_SUSPECT = 5
SMTP_MESSAGE_COUNT_HIGH = 20

# SYN Flood Rule
SYN_FLOOD_SYN_COUNT_SUSPECT = 20
SYN_FLOOD_SYN_COUNT_HIGH = 100
SYN_FLOOD_ACK_RATIO_MIN = 0.1
SYN_FLOOD_DURATION_MS_MAX = 5_000
SYN_FLOOD_DEST_CONCENTRATION_MIN = 15

# ICMP Flood Rule
ICMP_FLOOD_PPS_SUSPECT = 50
ICMP_FLOOD_PPS_HIGH = 200
ICMP_FLOOD_TOTAL_PKTS_SUSPECT = 100

# Top Talker Rule
TOP_TALKER_BPS_RATIO_SUSPECT = 5.0
TOP_TALKER_BPS_RATIO_HIGH = 20.0
TOP_TALKER_TOTAL_BYTES_SUSPECT = 1_000_000
TOP_TALKER_SHARE_OF_TRAFFIC_SUSPECT = 0.5

# HTTP Anomaly Rule
HTTP_ERROR_RATIO_SUSPECT = 0.5
HTTP_ERROR_RATIO_HIGH = 0.8
HTTP_SINGLE_URI_SHARE_SUSPECT = 0.7
HTTP_UNUSUAL_METHOD_SUSPECT = 5
HTTP_SCAN_UA_PATTERNS = ("nmap", "sqlmap", "nikto", "masscan", "wpscan", "curl", "python-requests")

# Beaconing Rule
BEACON_INTERVAL_MIN_MS = 100
BEACON_INTERVAL_MAX_MS = 60_000
BEACON_VARIANCE_RATIO_SUSPECT = 0.3
BEACON_VARIANCE_RATIO_HIGH = 0.05
BEACON_PACKET_COUNT_MIN = 10
BEACON_AVG_PKT_SIZE_MAX = 200
BEACON_DURATION_MIN_MS = 5_000

# Cleartext Credentials Rule
CLEARTEXT_LOGIN_URI_KEYWORDS = ("login", "signin", "auth", "authenticate", "token", "password")
CLEARTEXT_HTTP_PORT_MIN = 80
CLEARTEXT_HTTP_PORT_MAX = 8080

# Large Outbound Transfer Rule
LARGE_OUTBOUND_MIN_BYTES = 100_000_000  # 100 MB
LARGE_OUTBOUND_MIN_DURATION_SEC = 1.0
LARGE_OUTBOUND_SRC_BYTES_RATIO = 0.3  # ratio of src_bytes to total bytes
